// Mock data for development without backend

export const mockDashboardStats = {
  totalContacts: 156,
  totalDeals: 42,
  totalTasks: 28,
  totalCompanies: 34,
  activeDeals: 18,
  totalDealsAmount: 4850000,
  pendingTasks: 12,
  todayTasks: 5,
  highPriorityTasks: 3,
  recentContacts: 8,
  dealsAddedToday: 2,
  recentActivities: [
    {
      id: '1',
      type: 'DEAL_CREATED',
      description: 'Создана сделка "Поставка оборудования"',
      createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
      user: { firstName: 'Алексей', lastName: 'Иванов' },
    },
    {
      id: '2',
      type: 'CONTACT_CREATED',
      description: 'Добавлен контакт "Мария Петрова"',
      createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
      user: { firstName: 'Ольга', lastName: 'Смирнова' },
    },
    {
      id: '3',
      type: 'TASK_COMPLETED',
      description: 'Завершена задача "Подготовить КП"',
      createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
      user: { firstName: 'Дмитрий', lastName: 'Козлов' },
    },
    {
      id: '4',
      type: 'DEAL_UPDATED',
      description: 'Сделка "IT консалтинг" перемещена в "Переговоры"',
      createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
      user: { firstName: 'Алексей', lastName: 'Иванов' },
    },
    {
      id: '5',
      type: 'CONTACT_CREATED',
      description: 'Добавлен контакт "Сергей Николаев"',
      createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
      user: { firstName: 'Ольга', lastName: 'Смирнова' },
    },
  ],
  funnel: [
    { id: '1', name: 'Новые', color: '#6366f1', dealsCount: 8, totalAmount: 1200000 },
    { id: '2', name: 'Переговоры', color: '#8b5cf6', dealsCount: 5, totalAmount: 1500000 },
    { id: '3', name: 'КП отправлено', color: '#a855f7', dealsCount: 3, totalAmount: 850000 },
    { id: '4', name: 'Согласование', color: '#d946ef', dealsCount: 2, totalAmount: 800000 },
    { id: '5', name: 'Закрыто', color: '#22c55e', dealsCount: 4, totalAmount: 500000 },
  ],
};

export const mockTodayTasks = [
  {
    id: '1',
    title: 'Позвонить клиенту по сделке',
    dueDate: new Date(Date.now() + 2 * 3600000).toISOString(),
    priority: 'HIGH',
    contact: { firstName: 'Мария', lastName: 'Петрова' },
    deal: { title: 'Поставка оборудования' },
  },
  {
    id: '2',
    title: 'Подготовить презентацию',
    dueDate: new Date(Date.now() + 4 * 3600000).toISOString(),
    priority: 'MEDIUM',
    deal: { title: 'IT консалтинг' },
  },
  {
    id: '3',
    title: 'Встреча с партнером',
    dueDate: new Date(Date.now() + 5 * 3600000).toISOString(),
    priority: 'HIGH',
    contact: { firstName: 'Андрей', lastName: 'Сидоров' },
  },
  {
    id: '4',
    title: 'Отправить договор',
    dueDate: new Date(Date.now() + 6 * 3600000).toISOString(),
    priority: 'MEDIUM',
    deal: { title: 'Разработка сайта' },
  },
  {
    id: '5',
    title: 'Проверить оплату',
    dueDate: new Date(Date.now() + 7 * 3600000).toISOString(),
    priority: 'LOW',
    deal: { title: 'Маркетинговая кампания' },
  },
];

export const mockContacts = [
  {
    id: '1',
    firstName: 'Мария',
    lastName: 'Петрова',
    email: 'maria@example.com',
    phone: '+7 (999) 123-45-67',
    position: 'Директор',
    company: { id: '1', name: 'ООО "Технологии"' },
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
  {
    id: '2',
    firstName: 'Андрей',
    lastName: 'Сидоров',
    email: 'andrey@example.com',
    phone: '+7 (999) 234-56-78',
    position: 'Менеджер',
    company: { id: '2', name: 'АО "Инновации"' },
    createdAt: new Date(Date.now() - 14 * 86400000).toISOString(),
  },
  {
    id: '3',
    firstName: 'Елена',
    lastName: 'Козлова',
    email: 'elena@example.com',
    phone: '+7 (999) 345-67-89',
    position: 'CEO',
    company: { id: '3', name: 'ИП Козлова' },
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: '4',
    firstName: 'Сергей',
    lastName: 'Николаев',
    email: 'sergey@example.com',
    phone: '+7 (999) 456-78-90',
    position: 'Закупщик',
    company: { id: '1', name: 'ООО "Технологии"' },
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: '5',
    firstName: 'Ольга',
    lastName: 'Иванова',
    email: 'olga@example.com',
    phone: '+7 (999) 567-89-01',
    position: 'Финансовый директор',
    company: { id: '2', name: 'АО "Инновации"' },
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];

export const mockCompanies = [
  {
    id: '1',
    name: 'ООО "Технологии"',
    industry: 'IT',
    website: 'https://tech.example.com',
    phone: '+7 (495) 123-45-67',
    email: 'info@tech.example.com',
    address: 'г. Москва, ул. Технологическая, 15',
    contactsCount: 3,
    dealsCount: 5,
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: '2',
    name: 'АО "Инновации"',
    industry: 'Производство',
    website: 'https://innov.example.com',
    phone: '+7 (495) 234-56-78',
    email: 'info@innov.example.com',
    address: 'г. Санкт-Петербург, пр. Инновационный, 42',
    contactsCount: 2,
    dealsCount: 3,
    createdAt: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: '3',
    name: 'ИП Козлова',
    industry: 'Консалтинг',
    phone: '+7 (999) 345-67-89',
    email: 'kozlova@example.com',
    address: 'г. Казань, ул. Консультантов, 7',
    contactsCount: 1,
    dealsCount: 2,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const mockPipelines = [
  {
    id: '1',
    name: 'Основная воронка',
    stages: [
      { id: '1', name: 'Новые', color: '#6366f1', order: 0 },
      { id: '2', name: 'Переговоры', color: '#8b5cf6', order: 1 },
      { id: '3', name: 'КП отправлено', color: '#a855f7', order: 2 },
      { id: '4', name: 'Согласование', color: '#d946ef', order: 3 },
      { id: '5', name: 'Закрыто', color: '#22c55e', order: 4 },
    ],
  },
];

export const mockDeals = [
  {
    id: '1',
    title: 'Поставка оборудования',
    amount: 1500000,
    stageId: '1',
    stage: { id: '1', name: 'Новые', color: '#6366f1' },
    contact: { id: '1', firstName: 'Мария', lastName: 'Петрова' },
    company: { id: '1', name: 'ООО "Технологии"' },
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: '2',
    title: 'IT консалтинг',
    amount: 850000,
    stageId: '2',
    stage: { id: '2', name: 'Переговоры', color: '#8b5cf6' },
    contact: { id: '2', firstName: 'Андрей', lastName: 'Сидоров' },
    company: { id: '2', name: 'АО "Инновации"' },
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 3600000).toISOString(),
  },
  {
    id: '3',
    title: 'Разработка сайта',
    amount: 450000,
    stageId: '3',
    stage: { id: '3', name: 'КП отправлено', color: '#a855f7' },
    contact: { id: '3', firstName: 'Елена', lastName: 'Козлова' },
    company: { id: '3', name: 'ИП Козлова' },
    createdAt: new Date(Date.now() - 10 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: '4',
    title: 'Маркетинговая кампания',
    amount: 300000,
    stageId: '2',
    stage: { id: '2', name: 'Переговоры', color: '#8b5cf6' },
    contact: { id: '5', firstName: 'Ольга', lastName: 'Иванова' },
    company: { id: '2', name: 'АО "Инновации"' },
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: '5',
    title: 'Обучение персонала',
    amount: 200000,
    stageId: '1',
    stage: { id: '1', name: 'Новые', color: '#6366f1' },
    contact: { id: '4', firstName: 'Сергей', lastName: 'Николаев' },
    company: { id: '1', name: 'ООО "Технологии"' },
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
];

export const mockTasks = [
  {
    id: '1',
    title: 'Позвонить клиенту по сделке',
    description: 'Уточнить детали по поставке оборудования',
    dueDate: new Date(Date.now() + 2 * 3600000).toISOString(),
    priority: 'HIGH',
    status: 'PENDING',
    contact: { id: '1', firstName: 'Мария', lastName: 'Петрова' },
    deal: { id: '1', title: 'Поставка оборудования' },
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: '2',
    title: 'Подготовить презентацию',
    description: 'Презентация для встречи по IT консалтингу',
    dueDate: new Date(Date.now() + 4 * 3600000).toISOString(),
    priority: 'MEDIUM',
    status: 'PENDING',
    deal: { id: '2', title: 'IT консалтинг' },
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: '3',
    title: 'Встреча с партнером',
    description: 'Обсуждение условий сотрудничества',
    dueDate: new Date(Date.now() + 5 * 3600000).toISOString(),
    priority: 'HIGH',
    status: 'PENDING',
    contact: { id: '2', firstName: 'Андрей', lastName: 'Сидоров' },
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: '4',
    title: 'Отправить договор',
    description: 'Договор на разработку сайта',
    dueDate: new Date(Date.now() + 6 * 3600000).toISOString(),
    priority: 'MEDIUM',
    status: 'PENDING',
    deal: { id: '3', title: 'Разработка сайта' },
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: '5',
    title: 'Проверить оплату',
    description: 'Проверить поступление оплаты по сделке',
    dueDate: new Date(Date.now() + 7 * 3600000).toISOString(),
    priority: 'LOW',
    status: 'PENDING',
    deal: { id: '4', title: 'Маркетинговая кампания' },
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
];

export const mockLeads = [
  {
    id: '1',
    name: 'Заявка с сайта - Корпоративное обучение',
    source: 'website',
    status: 'NEW',
    email: 'lead1@example.com',
    phone: '+7 (999) 111-22-33',
    createdAt: new Date(Date.now() - 1 * 3600000).toISOString(),
  },
  {
    id: '2',
    name: 'Звонок - Интеграция CRM',
    source: 'call',
    status: 'IN_PROGRESS',
    email: 'lead2@example.com',
    phone: '+7 (999) 222-33-44',
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: '3',
    name: 'Email - Разработка приложения',
    source: 'email',
    status: 'NEW',
    email: 'lead3@example.com',
    phone: '+7 (999) 333-44-55',
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
];
