import {
  Loader2,
  Mail,
  Lock,
  Eye,
  EyeOff,
  User,
  Phone,
  Calendar,
  Search,
  Plus,
  Edit,
  Trash,
  Download,
  Upload,
  Filter,
  Settings,
  LogOut,
  Menu,
  X,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  Check,
  AlertCircle,
  Info,
  Building2,
  Users,
  Package,
  Target,
  MessageSquare,
  Bell,
  Home,
  BarChart,
  FileText,
  DollarSign,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  spinner: Loader2,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  user: User,
  phone: Phone,
  calendar: Calendar,
  search: Search,
  plus: Plus,
  edit: Edit,
  trash: Trash,
  download: Download,
  upload: Upload,
  filter: Filter,
  settings: Settings,
  logout: LogOut,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  check: Check,
  alert: AlertCircle,
  info: Info,
  building: Building2,
  users: Users,
  package: Package,
  target: Target,
  message: MessageSquare,
  bell: Bell,
  home: Home,
  chart: BarChart,
  file: FileText,
  dollar: DollarSign,
}