[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm exec prisma generate && pnpm run build"

[deploy]
startCommand = "pnpm exec prisma db push && pnpm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
